apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${appName}
  namespace: openshift-gitops
spec:
  destination:
    namespace: lab-workspace
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: ${appName}/src/main/jkube
    repoURL: https://github.com/kevbrain/${appName}.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true