allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
groups:
- system:cluster-admins
kind: SecurityContextConstraints
metadata:
  name: ${appName}-scc
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
fsGroup:
  type: MustRunAs
  ranges:
  - min: ${userGid}
    max: ${userGid}
runAsUser:
  type: MustRunAsRange
  uidRangeMin: ${userUid}
  uidRangeMax: ${userUid}
seLinuxContext:
  type: MustRunAs
supplementalGroups:
   type: MustRunAs
   ranges:
   - min: ${userGid}
     max: ${userGid}
users:
- system:serviceaccount:${appName}-{{bil.environment}}:${serviceAccount.name}
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- nfs