kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${appName}-pipeline-claim
  namespace: ${ocpNamespace}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
status:

