<#list persitentVolumes as pv>
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc${pv.claim.name}
  labels:
    app: ${appName}
spec:
  accessModes:
    - ${pv.claim.accessModes}
  resources:
    requests:
      storage: ${pv.claim.gbStorage}Gi
  storageClassName: ${pv.claim.storageClassName}
---
</#list>