<#list routes as route>
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${appName}-route
  labels:
    app: ${appName}
spec:
  host: >-
    ${appName}-${appName}.{{bil.environment}}.{{cluster-suffix}}
  to:
    kind: Service
    name: ${appName}-service
    weight: 256
  port:
    targetPort: '{{server.port}}'
  tls:
    termination: edge
  wildcardPolicy: None
---
</#list>